# Generated by Django 5.2.17 on 2026-10-01 13:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(db_index=True, max_length=16, validators=[django.core.validators.RegexValidator(code='invalid_fn', message='ФН должен состоять ровно из 16 цифр', regex='^\\d{16}$')], verbose_name='ФН')),
                ('fd', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_fd', message='ФД должен состоять из цифр (не более 10)', regex='^\\d{1,10}$')], verbose_name='ФД')),
                ('fp', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_fp', message='ФП должен состоять из цифр (не более 10)', regex='^\\d{1,10}$')], verbose_name='ФП')),
                ('purchased_at', models.DateTimeField(verbose_name='Дата и время покупки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма, ₽')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], db_index=True, default='pending', max_length=10, verbose_name='Статус')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Причина отказа')),
                ('photo', models.ImageField(blank=True, help_text='Бонус: JPG/PNG/WebP до 10 МБ', null=True, upload_to='receipts/%Y/%m/', verbose_name='Фото чека')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'чек',
                'verbose_name_plural': 'чеки',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted'])), fields=('fn', 'fd', 'fp'), name='unique_active_receipt')],
            },
        ),
    ]
