# Generated by Django 5.2.17 on 2026-10-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'чек', 'verbose_name_plural': 'чеки'},
        ),
    ]
