# Generated by Django 5.2.17 on 2026-10-01 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_alter_receipt_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='fd',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_fd', message='ФД должен состоять из цифр (не более 10)', regex='^\\d{1,10}$')], verbose_name='Номер чека (ФД)'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='purchased_at',
            field=models.DateTimeField(verbose_name='Дата покупки'),
        ),
    ]
