# Generated by Django 5.2.17 on 2026-10-01 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_alter_receipt_fd_alter_receipt_purchased_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['user', '-created_at'], name='receipt_user_created_idx'),
        ),
    ]
