# Generated by Django 5.2.17 on 2026-10-01 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_receipt_receipt_user_created_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='receipt',
            name='unique_active_receipt',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('accepted', 'Принят'), ('rejected', 'Отклонён'), ('won', 'Выиграл'), ('lost', 'Не повезло')], db_index=True, default='pending', max_length=10, verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted', 'won', 'lost'])), fields=('fn', 'fd', 'fp'), name='unique_active_receipt'),
        ),
    ]
